# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DMo-xVUkZKkzCQG2T21HHtweOub8gQZS
"""



import numpy as np

apple2 = np.array([[1,2,3], [4,5,6]])
apple1 = np.array([1,2,3,4,5,6])

sum_apple1 = np.sum(apple1)
sum_apple2 = np.sum(apple2)
mean_apple1 = np.mean(apple1)
mean_apple2 = np.mean(apple2)
prod_apple1 = np.prod(apple1)
prod_apple2 = np.prod(apple2)

print("1D massiv:", apple1)
print("2D massiv:\n", apple2)
print("1D yig'indisi:", sum_apple1)
print("1D o'rtachasi:", mean_apple1)
print("1D ko'paytmasi:", prod_apple1)
print("2D yig'indisi:", sum_apple2)
print("2D o'rtachasi:", mean_apple2)
print("2D ko'paytmasi:", prod_apple2)

import pandas as pd

data = {
    "Name": [ "Anvarjon", "Bunyod", "Muhammadayubxon", "Muhammadrizo", "Javohir",
             "Hakimjon", "Farruxbek", "Jasurbek", "Gulshanoy", "Zufarbek"],
    "Age": [ 18, 19, 19, 21, 19, 19, 19, 21, 19, 21, ],
    "City": [ "Farg'ona", "Farg'ona", "Farg'ona", "QOQON", "Quvasoy",
             "Farg'ona", "BESHARIQ", "Farg'ona", "Farg'ona", "VODIL"]
}
pdf = pd.DataFrame(data)

mahalliy = pdf[pdf["City"] == "Farg'ona"]


print("Fag'onaliklar soni",len(mahalliy), "\n", mahalliy)